# Generated by Django 3.2.3 on 2024-12-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20241219_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='hash',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Хэш'),
        ),
    ]
