# Generated by Django 3.2.3 on 2024-12-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_url_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
