# Generated by Django 3.2.3 on 2024-11-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Рецепт-Ингредиент', 'verbose_name_plural': 'Рецептыы-Ингредиенты'},
        ),
    ]
