# Generated by Django 3.2.3 on 2024-12-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20241210_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='hash',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='url',
            constraint=models.UniqueConstraint(fields=('hash', 'url'), name='unique_hash_url'),
        ),
    ]
