# Generated by Django 3.2.3 on 2024-12-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20241210_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='hash',
            field=models.CharField(max_length=255, unique=True, verbose_name='Хэш'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
